---
title: "Video Games Sales Project"
author: "Group7"
date: "today"
# date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

**Import Data**

```{r import}
game <- data.frame(read.csv("Video_Games_Sales_16-12-22.csv"))
game$Platform <- factor(game$Platform)
game$Genre <- factor(game$Genre)
game$User_Score <- as.numeric(game$User_Score)
#str(game)
gameclean <- na.omit(game)
sum(is.na(gameclean))
str(gameclean)
```

```{r test1}
summary(game$Platform)
game$Generation[game$Platform %in% c("PS3",  "X360", "Wii")] <- "7"
game$Generation[game$Platform %in% c("PS4",  "XOne", "WiiU")] <- "8"
#test.example1a <- subset(game, Platform %in% c("PS3",  "X360", "Wii"))
#test.example1b <- subset(game, Platform %in% c("PS4",  "XOne", "WiiU"))
summary(game$Generation)
```

```{r test plot}
library(ggplot2)
ggplot(game, aes(x=Generation, y=Global_Sales)) +
  geom_boxplot(color="pink", outlier.color="red") +
  labs(title="Global Sales vs Platform", x="Platform(7th & 8th Generation)", y="Global Sales") +
  coord_cartesian(ylim = c(0, 2))
#ggplot(test.example1a, aes(x=Platform, y=Global_Sales)) +
#  geom_boxplot(color="pink", outlier.color="red") +
#  labs(title="Global Sales vs Platform", x="Platform(7th Generation)", y="Global Sales") +
#  coord_cartesian(ylim = c(0, 2))
#ggplot(test.example1b, aes(x=Platform, y=Global_Sales)) +
#  geom_boxplot(color="pink", outlier.color="red") +
#  labs(title="Global Sales vs Platform", x="Platform(8th Generation)", y="Global Sales") +
#  coord_cartesian(ylim = c(0, 2))
```

```{r test2}
#test correlation
test.example2 <- subset(game, select=c(Platform,Genre, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales, Critic_Score, Critic_Count, User_Score, User_Count))
str(test.example2)
#pairs(test.example2)
gamenumeric <- subset(test.example2, select = -c(Platform,Genre))
gamenumeric <- na.omit(gamenumeric)
nrow(gamenumeric)
gamecor <- cor(gamenumeric)
loadPkg("corrplot")
corrplot(gamecor)
unloadPkg("corrplot")
```

