---
title: "Telco Customer Churn Project"
author: "Group7-Bug Tornado"
#date: "today"
date: "`r Sys.Date()`"
# this style requires installing rmdformats package 
output:  
    rmdformats::readthedown:
      toc_float: true
      toc_depth: 3
      number_sections: true
      code_folding: hide
      includes:
        before_body: header.html
---

```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
library(ggplot2)
library(ggpubr)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

**Import Data**

```{r import}
customer <- data.frame(read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv"))
str(customer)
#head(customer)
```

```{r asfactor}
for(i in 2:21){
  # tenure, MonthlyCharges, TotalCharges
  if (!(i %in% c(6, 19, 20))){
    customer[,i] = factor(customer[,i])
  }
}
levels(customer$SeniorCitizen) <- c("No", "Yes") # no=1, yes=2
str(customer)
```

```{r cleanNA}
summary(customer)  # there are 11 NA in TotalCharges
customer <- na.omit(customer)
sum(is.na(customer))
```


```{r basicInfo plot}
# gender seniorCitizen partner depedents
gender <- ggplot(customer, aes(x=gender, fill=Churn)) +
                  geom_bar(position="fill") +
                  scale_fill_manual(values=c("pink3", "steelblue")) +
                  labs(title="Gender", x="", y="Percentage") +
                  theme(legend.position="top")
senior <- ggplot(customer, aes(x=SeniorCitizen, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Not senior", "Yes" = "Senior")) +
                   labs(title="SeniorCitizen", x="", y="Percentage") +
                   theme(legend.position="top")
partner <- ggplot(customer, aes(x=Partner, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no partner", "Yes" = "Have a partner")) +
                   labs(title="Partner", x="", y="Percentage") +
                   theme(legend.position="top")
dependent <- ggplot(customer, aes(x=Dependents, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no dependents", "Yes" = "Have dependents")) +
                   labs(title="Dependent", x="", y="Percentage") +
                   theme(legend.position="top")
basicInfo <- ggarrange(gender, senior, partner, dependent)
annotate_figure(basicInfo, top = text_grob("Customer Basic Infomation", 
               color = "Black", face = "bold", size = 14))
```
```{r basic characteristics}
phone_service <- ggplot(customer, aes(x=PhoneService, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no phone service", "Yes" = "have phone services")) +
                   labs(title="Phone Service", x="", y="Percentage") +
                   theme(legend.position="top")
phone_service
multiple_lines <- ggplot(customer, aes(x=MultipleLines, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no multiple lines", "Yes" = "Have multiple lines")) +
                   labs(title="Multiple lines", x="", y="Percentage") +
                   theme(legend.position="top")
multiple_lines
internet_service <- ggplot(customer, aes(x=InternetService, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no internet service")) +
                   labs(title="Internet services", x="Internet company", y="Percentage") +
                   theme(legend.position="top")
internet_service
online_security <- ggplot(customer, aes(x=OnlineSecurity, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no online security", "Yes" = "have online security")) +
                   labs(title="Online security", x="", y="Percentage") +
                   theme(legend.position="top")
online_security
online_backup <- ggplot(customer, aes(x=OnlineBackup, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no online backup", "Yes" = "Have online backup")) +
                   labs(title="Online backup", x="", y="Percentage") +
                   theme(legend.position="top")
online_backup
device_protection <- ggplot(customer, aes(x=DeviceProtection, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no device protection", "Yes" = "Have device protection")) +
                   labs(title="Device protection", x="", y="Percentage") +
                   theme(legend.position="top")
device_protection
tech_support <- ggplot(customer, aes(x=TechSupport, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no tech support", "Yes" = "Have tech support")) +
                   labs(title="Tech support", x="", y="Percentage") +
                   theme(legend.position="top")
tech_support
streaming_TV <- ggplot(customer, aes(x=StreamingTV, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no streaming tv", "Yes" = "Have streaming tv")) +
                   labs(title="Streaming tv", x="", y="Percentage") +
                   theme(legend.position="top")
streaming_TV
streaming_movies <- ggplot(customer, aes(x=StreamingMovies, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no streaming movies", "Yes" = "Have streaming movies")) +
                   labs(title="Streaming movies", x="", y="Percentage") +
                   theme(legend.position="top")
streaming_movies
contract <- ggplot(customer, aes(x=Contract, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   labs(title="Contract", x="Method", y="Percentage") +
                   theme(legend.position="top")
contract
paperless_billing <- ggplot(customer, aes(x=PaperlessBilling, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   scale_x_discrete(labels=c("No" = "Have no paperless billing", "Yes" = "Have paperless billing")) +
                   labs(title="Paperless billing", x="", y="Percentage") +
                   theme(legend.position="top")
paperless_billing
payment_method <- ggplot(customer, aes(x=PaymentMethod, fill=Churn)) +
                   geom_bar(position="fill") +
                   scale_fill_manual(values=c("pink3", "steelblue")) +
                   labs(title="Payment method", x="Method", y="Percentage") +
                   theme(legend.position="top")
payment_method


```


```{r correlationPlot}
customerNum = customer
# convert categorical variable as numeric for spearman method
for(i in 2:21){
  # tenure, MonthlyCharges, TotalCharges
  if (!(i %in% c(6, 19, 20))){
    customerNum[,i] = as.numeric(customerNum[,i])
  }
}
#str(customerNum)

# corrplot with spearman method for categorical variables
customercor <- cor(subset(customerNum, select=-c(customerID)), method="spearman")
#customercor
loadPkg("corrplot")
#corrplot.mixed(customercor, tl.pos = "lt", number.cex = .5, tl.cex=0.8)
corrplot(customercor, addCoef.col="black", number.cex=0.4, tl.cex=0.6,title="Telco Customer Churn Correlation", mar=c(0,0,1,0))
unloadPkg("corrplot")
```

```{r kdePlot}
tenure <- ggplot(data = customer, aes(x = tenure, color = Churn)) + 
            geom_density(aes(fill = Churn), alpha = 0.8) + 
             labs(title="KDEplot for tenure") +
              labs(x="tenure", y="density") +
               theme(legend.position="top")
tenure

MonthlyCharges <- ggplot(data = customer, aes(x = MonthlyCharges, color = Churn)) + 
                   geom_density(aes(fill = Churn), alpha = 0.8) + 
                    labs(title="KDEplot for MonthlyCharges") +
                     labs(x="MonthlyCharges", y="density") +
                      theme(legend.position="top")
MonthlyCharges

TotalCharges <- ggplot(data = customer, aes(x = TotalCharges, color = Churn)) + 
                   geom_density(aes(fill = Churn), alpha = 0.8) + 
                    labs(title="KDEplot for TotalCharges") +
                     labs(x="TotalCharges", y="density") +
                      theme(legend.position="top")
TotalCharges
```


